##多数据源
datasource:
  #主库
  master:
    jdbcUrl: jdbc:mysql://80.8.100.103:3306/im-user-server-core?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ilonw!QAZ@WSX
    driver-class-name: com.mysql.jdbc.Driver

  #从库
  slave:
    #并非url而是jdbcUrl(因为这个在获取数据源时一直报错，看了DataSource的属性才知道是jdbcUrl)
    jdbcUrl: jdbc:mysql://80.8.100.103:3306/im-server-log?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ilonw!QAZ@WSX
    driver-class-name: com.mysql.jdbc.Driver

spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

  # Redis数据库索引（默认为0）
  redis:
    database: 0
    host: 80.8.100.103
    port: 6739
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000


##mybatis
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.im.user.server.domain
  check-config-location: true
  config-location: classpath:mybatis-config.xml

dubbo:
  registry:
    address: 80.8.100.100:2181,80.8.100.101:2181,80.8.100.102:2181
  port: 20880
  threadpool:
    size: 100
  timeout: 30000